fix release-jar workflow

diff --git a/.github/workflows/release-jar.yaml b/.github/workflows/release-jar.yaml
--- a/.github/workflows/release-jar.yaml
+++ b/.github/workflows/release-jar.yaml
@@ -33,7 +33,17 @@ jobs:
 
       - name: Get tag name
         id: get_tag
-        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
+        run: |
+          if [[ "${{ github.event_name }}" == "push" ]]; then
+            TAG_NAME="${GITHUB_REF#refs/tags/}"
+          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            TAG_NAME="${{ github.event.inputs.tag_name }}"
+          else
+            echo "Error: Workflow triggered by unsupported event type: ${{ github.event_name }}"
+            exit 1
+          fi
+          echo "Extracted tag name: $TAG_NAME"
+          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
 
       - name: Create GitHub Release
         id: create_release
